# This rule is not used by the project distributed-auth-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to auth.pure-o.pl resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: distributed-auth-operator
    app.kubernetes.io/managed-by: kustomize
  name: authcluster-viewer-role
rules:
- apiGroups:
  - auth.pure-o.pl
  resources:
  - authclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.pure-o.pl
  resources:
  - authclusters/status
  verbs:
  - get
