# This rule is not used by the project distributed-auth-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over auth.pure-o.pl.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: distributed-auth-operator
    app.kubernetes.io/managed-by: kustomize
  name: authcluster-admin-role
rules:
- apiGroups:
  - auth.pure-o.pl
  resources:
  - authclusters
  verbs:
  - '*'
- apiGroups:
  - auth.pure-o.pl
  resources:
  - authclusters/status
  verbs:
  - get
