apiVersion: batch/v1
kind: Job
metadata:
  name: demo-client
spec:
  template:
    spec:
      containers:
        - name: client
          image: distributed-auth-system-demo-client:latest
          imagePullPolicy: IfNotPresent
          command: ["/app/run-demo.sh"]
      restartPolicy: Never